### ISSUE TITLE
Wrong test syntax in "shield-trigger-iptables" script

### ISSUE THREAD

**Issue by arnaudf92** [h0tw1r3/pam_shield#1]
Hello,

Just tried pam-shield module, and thank you for it.
I open this issue because there is a wrong test syntax in "shield-trigger-iptables" script at lines 37 and 45.

These tests have to use the = (equal sign) operator, and not == (double equal sign). If not the script fails.
Reference : https://linuxcommand.org/lc3_man_pages/testh.html

Regards.

**Comment by h0tw1r3** [comment]
Fixed by ae51020
